import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { MessageSquare, Mic, MicOff } from "lucide-react";
import { toast } from "@/components/ui/use-toast";

export const ChatInterface = () => {
  const [message, setMessage] = useState("");
  const [isRecording, setIsRecording] = useState(false);
  const [responses, setResponses] = useState<Array<{ question: string; answer: string }>>([]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (message.trim()) {
      const newResponse = {
        question: message,
        answer: "This is a sample AI response to your question. In a real implementation, this would be generated by our AI model.",
      };
      setResponses([newResponse, ...responses]);
      setMessage("");
    }
  };

  const handleQuestionClick = (question: string) => {
    setMessage(question);
    handleSubmit(new Event('submit') as any);
  };

  const toggleVoiceRecording = async () => {
    try {
      if (!isRecording) {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
        setIsRecording(true);
        toast({
          title: "Recording started",
          description: "Speak your message...",
        });
      } else {
        setIsRecording(false);
        toast({
          title: "Recording stopped",
          description: "Processing your message...",
        });
      }
    } catch (error) {
      toast({
        title: "Error",
        description: "Could not access microphone",
        variant: "destructive",
      });
    }
  };

  const suggestedQuestions = [
    "What are the main topics covered?",
    "Can you explain the key points?",
    "What is the conclusion?",
  ];

  return (
    <div className="space-y-4 animate-slide-in">
      <div className="glass rounded-lg p-4 bg-white/80">
        <h3 className="text-lg font-semibold mb-3">Suggested Questions</h3>
        <div className="space-y-2">
          {suggestedQuestions.map((question, index) => (
            <Button
              key={index}
              variant="secondary"
              className="w-full justify-start text-left text-sm bg-white/50 hover:bg-white/80 transition-colors"
              onClick={() => handleQuestionClick(question)}
            >
              {question}
            </Button>
          ))}
        </div>
      </div>

      {responses.length > 0 && (
        <div className="space-y-4 max-h-60 overflow-y-auto scrollbar-thin scrollbar-thumb-gray-200">
          {responses.map((response, index) => (
            <div key={index} className="bg-white/50 rounded-lg p-3 space-y-2">
              <p className="text-sm font-medium text-primary">{response.question}</p>
              <p className="text-sm text-gray-600">{response.answer}</p>
            </div>
          ))}
        </div>
      )}

      <form onSubmit={handleSubmit} className="flex gap-2">
        <Input
          type="text"
          placeholder="Ask a question about the video..."
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          className="flex-1 bg-white border-gray-200 focus:border-primary/50 focus:ring-primary/50"
        />
        <Button
          type="button"
          variant="secondary"
          size="icon"
          className={`${
            isRecording 
              ? 'bg-red-100 text-red-600 hover:bg-red-200' 
              : 'bg-white hover:bg-gray-50'
          } transition-colors`}
          onClick={toggleVoiceRecording}
        >
          {isRecording ? <MicOff className="h-4 w-4" /> : <Mic className="h-4 w-4" />}
        </Button>
        <Button 
          type="submit" 
          size="icon"
          className="bg-gradient-to-r from-primary to-secondary hover:opacity-90"
        >
          <MessageSquare className="h-4 w-4" />
        </Button>
      </form>
    </div>
  );
};
