// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsptkurmulwpouyadhqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcHRrdXJtdWx3cG91eWFkaHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjc1MDgsImV4cCI6MjA1NTgwMzUwOH0.QI5XtCzWdO83zsO-x_2a6bKtmwv78shW6UNYREkUSaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);